using Microsoft.EntityFrameworkCore.Migrations;

namespace Maze.Migrations
{
    public partial class ImgsAndImgMaps : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Doors",
                table: "Pages",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Img",
                table: "Pages",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: true);

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 1,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/1.PNG' usemap='#pg1-image-map' >\r\n                <map name='pg1-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 20'\r\n                    data-index=''\r\n                    data-title='20'\r\n                    href='/Maze/index/20'\r\n                    onclick = 'show('20.PNG')'\r\n                    coords='223,84,299,117'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 26'\r\n                    data-index=''\r\n                    data-title='26'\r\n                    href='/Maze/index/26'\r\n                    onclick = 'show('26.PNG')'\r\n                    coords='431,81,510,117'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 41'\r\n                    data-index=''\r\n                    data-title='41'\r\n                    href='/Maze/index/41'\r\n                    onclick = 'show('41.PNG')'\r\n                    coords='586,115,649,113,641,71,585,78'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 21'\r\n                    data-index=''\r\n                    data-title='21'\r\n                    href='/Maze/index/21'\r\n                    onclick = 'show('21.PNG')'\r\n                    coords='698,61,701,110,772,105,767,55'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/1.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 2,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/2.PNG' usemap='#pg2-image-map' >\r\n                <map name='pg2-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 29'\r\n                    data-index='29'\r\n                    data-title='29'\r\n                    href='/Maze/index/29'\r\n                    onclick = 'show('29.PNG')'\r\n                    coords='89,80,91,184,156,184,156,93'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 22'\r\n                    data-index='22'\r\n                    data-title='22'\r\n                    href='/Maze/index/22'\r\n                    onclick = 'show('22.PNG')'\r\n                    coords='359,111,358,177,461,178,460,112'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 12'\r\n                    data-index='12'\r\n                    data-title='12'\r\n                    href='/Maze/index/12'\r\n                    onclick = 'show('12.PNG')'\r\n                    coords='654,82,668,172,726,173,711,73'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/2.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 3,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/3.PNG' usemap='#pg3-image-map' >\r\n                <map name='pg3-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 9'\r\n                    data-index='9'\r\n                    data-title='9'\r\n                    href='/Maze/index/9'\r\n                    onclick = 'show('9.PNG')'\r\n                    coords='446,64,549,117'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 18'\r\n                    data-index='18'\r\n                    data-title='18'\r\n                    href='/Maze/index/18'\r\n                    onclick = 'show('18.PNG')'\r\n                    coords='671,45,666,112,750,107,755,25'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/3.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 4,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/4.PNG' usemap='#pg4-image-map' >\r\n                <map name='pg4-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 44'\r\n                    data-index='44'\r\n                    data-title='44'\r\n                    href='/Maze/index/44'\r\n                    onclick = 'show('44.PNG')'\r\n                    coords='74,41,53,115,163,137,179,82'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 29'\r\n                    data-index='29'\r\n                    data-title='29'\r\n                    href='/Maze/index/29'\r\n                    onclick = 'show('29.PNG')'\r\n                    coords='231,100,218,148,264,159,277,118'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 15'\r\n                    data-index='15'\r\n                    data-title='15'\r\n                    href='/Maze/index/15'\r\n                    onclick = 'show('15.PNG')'\r\n                    coords='300,125,288,164,312,168,322,136'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 11'\r\n                    data-index='11'\r\n                    data-title='11'\r\n                    href='/Maze/index/11'\r\n                    onclick = 'show('11.PNG')'\r\n                    coords='371,148,442,183'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 16'\r\n                    data-index='16'\r\n                    data-title='16'\r\n                    href='/Maze/index/16'\r\n                    onclick = 'show('16.PNG')'\r\n                    coords='492,135,502,170,527,164,515,125'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 24'\r\n                    data-index='24'\r\n                    data-title='24'\r\n                    href='/Maze/index/24'\r\n                    onclick = 'show('24.PNG')'\r\n                    coords='540,118,553,161,598,153,583,102'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/dbcontext43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='634,81,655,142,766,122,746,42'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n              ", "../wwwroot/images/4.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 5,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/5.PNG' usemap='#pg5-image-map' />\r\n                <map name='pg5-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='85,124,63,192,116,186,154,188,157,131,105,126'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 22'\r\n                    data-index='22'\r\n                    data-title='22'\r\n                    href='/Maze/index/22'\r\n                    onclick = 'show('22.PNG')'\r\n                    coords='264,122,264,140,258,178,291,172,322,171,344,176,354,146,337,124,302,125'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 30'\r\n                    data-index='30'\r\n                    data-title='30'\r\n                    href='/Maze/index/30'\r\n                    onclick = 'show('30.PNG')'\r\n                    coords='551,134,517,134,486,124,475,149,468,178,543,177'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 20'\r\n                    data-index='20'\r\n                    data-title='20'\r\n                    href='/Maze/index/20'\r\n                    onclick = 'show('20.PNG')'\r\n                    coords='655,144,643,198,716,196,722,140'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/5.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 6,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/6.PNG' usemap='#pg6-image-map' />\r\n                <map name='pg6-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 40'\r\n                    data-index='40'\r\n                    data-title='40'\r\n                    href='/Maze/index/40'\r\n                    onclick = 'show('40.PNG')'\r\n                    coords='147,147,122,206,208,255,237,195'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/6.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 7,
                columns: new[] { "Doors", "Img", "Text" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/7.PNG' usemap='#pg7-image-map' />\r\n                <map name='pg7-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 33'\r\n                    data-index='33'\r\n                    data-title='33'\r\n                    href='/Maze/index/33'\r\n                    onclick = 'show('33.PNG')'\r\n                    coords='96,18,97,80,173,86,175,37'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 36'\r\n                    data-index='36'\r\n                    data-title='36'\r\n                    href='/Maze/index/36'\r\n                    onclick = 'show('36.PNG')'\r\n                    coords='350,47,451,89'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 16'\r\n                    data-index='16'\r\n                    data-title='16'\r\n                    href='/Maze/index/16'\r\n                    onclick = 'show('16.PNG')'\r\n                    coords='635,34,635,85,707,79,705,20'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/7.PNG", ". . . a pleasant room with three doors and a lamp. Looking at the picture on the wall they decided it wasn't a very good likeness. One of them almost fell over something on the floor. 'Why don’t they pick up after themselves?' he said, sounding like an old man. 'Weren’t you ever irresponsible?' I asked, thinking of my childhood and how wild I had been. Music was being played somewhere nearby. We stopped to listen for a moment. Leaving the picture looking out at an empty room we went on to . . ." });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 8,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/8.PNG' usemap='#pg8-image-map' />\r\n                <map name='pg8-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 31'\r\n                    data-index='31'\r\n                    data-title='31'\r\n                    href='/Maze/index/31'\r\n                    onclick = 'show('31.PNG')'\r\n                    coords='12,233,12,295,18,337,136,296,99,220'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 6'\r\n                    data-index='6'\r\n                    data-title='6'\r\n                    href='/Maze/index/6'\r\n                    onclick = 'show('6.PNG')'\r\n                    coords='200,209,198,236,198,257,211,259,215,268,254,256,231,206'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 29'\r\n                    data-index='29'\r\n                    data-title='29'\r\n                    href='/Maze/index/29'\r\n                    onclick = 'show('29.PNG')'\r\n                    coords='314,177,339,225,423,189,398,136'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 12'\r\n                    data-index='12'\r\n                    data-title='12'\r\n                    href='/Maze/index/12'\r\n                    onclick = 'show('12.PNG')'\r\n                    coords='472,94,495,145,532,121,529,115,534,108,519,95,494,76'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/8.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 9,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/9.PNG' usemap='#pg9-image-map' />\r\n                <map name='pg9-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 3'\r\n                    data-index='3'\r\n                    data-title='3'\r\n                    href='/Maze/index/3'\r\n                    onclick = 'show('3.PNG')'\r\n                    coords='85,140,84,174,66,169,64,209,164,229,164,200,148,196,150,166,121,155'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 18'\r\n                    data-index='18'\r\n                    data-title='18'\r\n                    href='/Maze/index/18'\r\n                    onclick = 'show('18.PNG')'\r\n                    coords='530,162,530,185,502,186,503,208,656,210,656,187,630,186,628,163'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/9.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 10,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/10.PNG' usemap='#pg10-image-map' />\r\n                <map name='pg10-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 34'\r\n                    data-index='34'\r\n                    data-title='34'\r\n                    href='/Maze/index/34'\r\n                    onclick = 'show('34.PNG')'\r\n                    coords='46,60,56,125,139,125,133,59'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 41'\r\n                    data-index='41'\r\n                    data-title='41'\r\n                    href='/Maze/index/41'\r\n                    onclick = 'show('41.PNG')'\r\n                    coords='427,63,482,58,500,130,443,127'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 14'\r\n                    data-index='14'\r\n                    data-title='14'\r\n                    href='/Maze/index/14'\r\n                    onclick = 'show('14.PNG')'\r\n                    coords='594,51,674,44,692,143,612,138'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/10.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 11,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/11.PNG' usemap='#pg11-image-map' />\r\n                <map name='pg11-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 40'\r\n                    data-index='40'\r\n                    data-title='40'\r\n                    href='/Maze/index/40'\r\n                    onclick = 'show('40.PNG')'\r\n                    coords='115,214,208,417'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 24'\r\n                    data-index='24'\r\n                    data-title='24'\r\n                    href='/Maze/index/24'\r\n                    onclick = 'show('24.PNG')'\r\n                    coords='594,214,685,417'\r\n                    shape='rect' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/11.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 12,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/12.PNG' usemap='#pg12-image-map' />\r\n                <map name='pg12-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 2'\r\n                    data-index='2'\r\n                    data-title='2'\r\n                    href='/Maze/index/2'\r\n                    onclick = 'show('2.PNG')'\r\n                    coords='150,31,146,47,135,56,130,123,185,124,192,61,185,50,185,40'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 21'\r\n                    data-index='21'\r\n                    data-title='21'\r\n                    href='/Maze/index/21'\r\n                    onclick = 'show('21.PNG')'\r\n                    coords='366,66,373,61,376,53,421,54,427,62,438,69,438,124,365,125'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 8'\r\n                    data-index='8'\r\n                    data-title='8'\r\n                    href='/Maze/index/8'\r\n                    onclick = 'show('8.PNG')'\r\n                    coords='630,42,663,36,667,46,675,53,681,124,629,125,624,62,630,56'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 39'\r\n                    data-index='39'\r\n                    data-title='39'\r\n                    href='/Maze/index/39'\r\n                    onclick = 'show('39.PNG')'\r\n                    coords='286,431,352,408,376,430,362,461,316,471,303,481'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/12.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 13,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/13.PNG' usemap='#pg13-image-map' />\r\n                <map name='pg13-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 27'\r\n                    data-index='27'\r\n                    data-title='27'\r\n                    href='/Maze/index/27'\r\n                    onclick = 'show('27.PNG')'\r\n                    coords='39,9,72,9,131,31,130,93,39,67'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 18'\r\n                    data-index='18'\r\n                    data-title='18'\r\n                    href='/Maze/index/18'\r\n                    onclick = 'show('18.PNG')'\r\n                    coords='338,70,465,124'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 25'\r\n                    data-index='25'\r\n                    data-title='25'\r\n                    href='/Maze/index/25'\r\n                    onclick = 'show('25.PNG')'\r\n                    coords='672,34,732,8,762,9,759,67,672,98'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/13.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 14,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/14.PNG' usemap='#pg14-image-map' />\r\n                <map name='pg14-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 10'\r\n                    data-index='10'\r\n                    data-title='10'\r\n                    href='/Maze/index/10'\r\n                    onclick = 'show('10.PNG')'\r\n                    coords='36,272,50,264,63,262,75,254,113,236,122,238,147,298,102,316,63,331'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='363,208,383,212,424,217,459,214,458,234,462,253,473,274,417,272,353,269,354,238'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 24'\r\n                    data-index='24'\r\n                    data-title='24'\r\n                    href='/Maze/index/24'\r\n                    onclick = 'show('24.PNG')'\r\n                    coords='644,212,729,230,703,299,614,276'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/14.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 15,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/15.PNG' usemap='#pg15-image-map' />\r\n                <map name='pg15-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 30'\r\n                    data-index='30'\r\n                    data-title='30'\r\n                    href='/Maze/index/30'\r\n                    onclick = 'show('30.PNG')'\r\n                    coords='223,129,339,171'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 37'\r\n                    data-index='37'\r\n                    data-title='37'\r\n                    href='/Maze/index/37'\r\n                    onclick = 'show('37.PNG')'\r\n                    coords='456,127,572,171'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 3'\r\n                    data-index='3'\r\n                    data-title='3'\r\n                    href='/Maze/index/3'\r\n                    onclick = 'show('3.PNG')'\r\n                    coords='654,117,721,103,721,165,654,169'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/15.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 16,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/16.PNG' usemap='#pg16-image-map' />\r\n                <map name='pg16-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 36'\r\n                    data-index='36'\r\n                    data-title='36'\r\n                    href='/Maze/index/36'\r\n                    onclick = 'show('36.PNG')'\r\n                    coords='60,17,118,45,115,85,108,90,58,70'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 7'\r\n                    data-index='7'\r\n                    data-title='7'\r\n                    href='/Maze/index/7'\r\n                    onclick = 'show('7.PNG')'\r\n                    coords='669,39,726,17,728,74,670,90'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/16.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 17,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/17.PNG' usemap='#pg17-image-map' />\r\n                <map name='pg17-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 6'\r\n                    data-index='6'\r\n                    data-title='6'\r\n                    href='/Maze/index/6'\r\n                    onclick = 'show('6.PNG')'\r\n                    coords='34,315,63,300,90,301,104,306,91,355,61,361,51,336,44,321'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 45'\r\n                    data-index='45'\r\n                    data-title='45'\r\n                    href='/Maze/index/45'\r\n                    onclick = 'show('45.PNG')'\r\n                    coords='366,28,371,24,427,23,428,28,423,34,434,41,434,57,427,77,416,91,399,104,377,93,367,79,361,61,360,44,373,35,371,31'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 33'\r\n                    data-index='33'\r\n                    data-title='33'\r\n                    href='/Maze/index/33'\r\n                    onclick = 'show('33.PNG')'\r\n                    coords='649,90,740,67,743,142,649,150'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/17.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 18,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/18.PNG' usemap='#pg18-image-map' />\r\n                <map name='pg18-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 13'\r\n                    data-index='13'\r\n                    data-title='13'\r\n                    href='/Maze/index/13'\r\n                    onclick = 'show('13.PNG')'\r\n                    coords='363,95,452,93,458,108,458,145,367,144'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 3'\r\n                    data-index='3'\r\n                    data-title='3'\r\n                    href='/Maze/index/3'\r\n                    onclick = 'show('3.PNG')'\r\n                    coords='667,92,753,142'\r\n                    shape='rect' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/18.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 19,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/19.PNG' usemap='#pg19-image-map' />\r\n                <map name='pg19-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 31'\r\n                    data-index='31'\r\n                    data-title='31'\r\n                    href='/Maze/index/31'\r\n                    onclick = 'show('31.PNG')'\r\n                    coords='179,10,187,10,283,38,284,117,177,97'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 11'\r\n                    data-index='11'\r\n                    data-title='11'\r\n                    href='/Maze/index/11'\r\n                    onclick = 'show('11.PNG')'\r\n                    coords='333,54,394,71,393,135,333,125'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/19.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 20,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/20.PNG' usemap='#pg20-image-map' />\r\n                <map name='pg20-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 5'\r\n                    data-index='5'\r\n                    data-title='5'\r\n                    href='/Maze/index/5'\r\n                    onclick = 'show('5.PNG')'\r\n                    coords='50,28,105,36,104,92,49,89'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 27'\r\n                    data-index='27'\r\n                    data-title='27'\r\n                    href='/Maze/index/27'\r\n                    onclick = 'show('27.PNG')'\r\n                    coords='497,44,563,45,563,101,495,98'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 1'\r\n                    data-index='1'\r\n                    data-title='1'\r\n                    href='/Maze/index/1'\r\n                    onclick = 'show('1.PNG')'\r\n                    coords='705,42,763,35,763,99,704,100'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/20.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 21,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/21.PNG' usemap='#pg21-image-map' />\r\n                <map name='pg21-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 44'\r\n                    data-index='44'\r\n                    data-title='44'\r\n                    href='/Maze/index/44'\r\n                    onclick = 'show('44.PNG')'\r\n                    coords='77,167,155,178,131,249,98,246'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 24'\r\n                    data-index='24'\r\n                    data-title='24'\r\n                    href='/Maze/index/24'\r\n                    onclick = 'show('24.PNG')'\r\n                    coords='427,210,481,217,462,260,438,257'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 31'\r\n                    data-index='31'\r\n                    data-title='31'\r\n                    href='/Maze/index/31'\r\n                    onclick = 'show('31.PNG')'\r\n                    coords='685,240,688,232,726,232,728,238,715,266,692,265'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/21.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 22,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/22.PNG' usemap='#pg22-image-map' />\r\n                <map name='pg22-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='222,117,231,121,238,128,242,138,243,151,242,166,237,174,230,182,220,185,209,183,199,174,194,160,194,146,197,136,200,128,208,121,213,118'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 38'\r\n                    data-index='38'\r\n                    data-title='38'\r\n                    href='/Maze/index/38'\r\n                    onclick = 'show('38.PNG')'\r\n                    coords='579,118,589,118,597,124,604,134,607,144,607,154,605,165,599,173,593,179,582,183,572,179,564,174,558,164,556,157,556,146,560,135,566,125,573,120'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/22.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 23,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/23.PNG' usemap='#pg23-image-map' />\r\n                <map name='pg23-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 28'\r\n                    data-index='28'\r\n                    data-title='28'\r\n                    href='/Maze/index/28'\r\n                    onclick = 'show('28.PNG')'\r\n                    coords='40,102,128,154'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 8'\r\n                    data-index='8'\r\n                    data-title='8'\r\n                    href='/Maze/index/8'\r\n                    onclick = 'show('8.PNG')'\r\n                    coords='244,102,342,155'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 45'\r\n                    data-index='45'\r\n                    data-title='45'\r\n                    href='/Maze/index/45'\r\n                    onclick = 'show('45.PNG')'\r\n                    coords='444,102,551,155'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 19'\r\n                    data-index='19'\r\n                    data-title='19'\r\n                    href='/Maze/index/19'\r\n                    onclick = 'show('19.PNG')'\r\n                    coords='675,87,752,73,753,124,675,131'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/23.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 24,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/24.PNG' usemap='#pg24-image-map' />\r\n                <map name='pg24-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 0'\r\n                    data-index='0'\r\n                    data-title='0'\r\n                    href='/Maze/index/'\r\n                    onclick = 'show('.PNG')'\r\n                    coords='7,6,781,623'\r\n                    shape='rect' />\r\n                </map>\r\n            </img>\r\n            ", "../wwwroot/images/24.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 25,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/25.PNG' usemap='#pg25-image-map' />\r\n                <map name='pg25-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 34'\r\n                    data-index='34'\r\n                    data-title='34'\r\n                    href='/Maze/index/34'\r\n                    onclick = 'show('34.PNG')'\r\n                    coords='12,183,150,182,178,248,44,249'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 13'\r\n                    data-index='13'\r\n                    data-title='13'\r\n                    href='/Maze/index/13'\r\n                    onclick = 'show('13.PNG')'\r\n                    coords='230,182,356,163,368,246,243,264'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 35'\r\n                    data-index='35'\r\n                    data-title='35'\r\n                    href='/Maze/index/35'\r\n                    onclick = 'show('35.PNG')'\r\n                    coords='647,173,779,175,751,254,623,251'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/25.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 26,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/26.PNG' usemap='#pg26-image-map' />\r\n                <map name='pg26-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 30'\r\n                    data-index='30'\r\n                    data-title='30'\r\n                    href='/Maze/index/30'\r\n                    onclick = 'show('30.PNG')'\r\n                    coords='60,165,76,139,88,122,97,106,103,96,115,112,123,126,128,145,132,165,134,187,58,174'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 36'\r\n                    data-index='36'\r\n                    data-title='36'\r\n                    href='/Maze/index/36'\r\n                    onclick = 'show('36.PNG')'\r\n                    coords='184,190,191,169,199,154,208,142,224,126,235,133,250,141,260,146,270,151,286,155,292,165,296,179,299,191,191,192,184,190,185,179'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 38'\r\n                    data-index='38'\r\n                    data-title='38'\r\n                    href='/Maze/index/38'\r\n                    onclick = 'show('38.PNG')'\r\n                    coords='497,189,500,169,506,157,515,143,524,133,537,124,546,118,557,115,565,118,575,121,585,131,591,138,598,147,606,158,609,166,612,177,614,187'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 1'\r\n                    data-index='1'\r\n                    data-title='1'\r\n                    href='/Maze/index/1'\r\n                    onclick = 'show('1.PNG')'\r\n                    coords='666,184,666,171,667,162,671,148,674,136,678,125,683,111,688,103,697,95,701,108,708,119,715,132,722,144,727,152,728,158,735,164,733,173'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/26.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 27,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/27.PNG' usemap='#pg27-image-map' />\r\n                <map name='pg27-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 13'\r\n                    data-index='13'\r\n                    data-title='13'\r\n                    href='/Maze/index/13'\r\n                    onclick = 'show('13.PNG')'\r\n                    coords='173,117,196,107,206,107,189,145,189,149,186,153,180,158,179,164,124,164,129,154,124,146,132,140,139,119,149,99,163,110'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 9'\r\n                    data-index='9'\r\n                    data-title='9'\r\n                    href='/Maze/index/9'\r\n                    onclick = 'show('9.PNG')'\r\n                    coords='384,472,379,439,397,433,420,430,431,432,436,451,428,472'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/27.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 28,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/28.PNG' usemap='#pg28-image-map' />\r\n                <map name='pg28-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 23'\r\n                    data-index='23'\r\n                    data-title='23'\r\n                    href='/Maze/index/23'\r\n                    onclick = 'show('23.PNG')'\r\n                    coords='138,45,143,35,145,29,182,37,181,46,184,53,187,58,181,121,125,121,131,50'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='359,64,369,58,373,50,418,49,421,58,429,62,435,66,434,121,360,121'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 45'\r\n                    data-index='45'\r\n                    data-title='45'\r\n                    href='/Maze/index/45'\r\n                    onclick = 'show('45.PNG')'\r\n                    coords='618,57,623,51,623,40,656,31,660,41,672,50,678,114,673,121,623,121'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 32'\r\n                    data-index='32'\r\n                    data-title='32'\r\n                    href='/Maze/index/32'\r\n                    onclick = 'show('32.PNG')'\r\n                    coords='281,429,291,420,310,417,351,406,373,427,360,455,347,462,329,464,316,468,301,478'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/28.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 29,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/29.PNG' usemap='#pg29-image-map' />\r\n                <map name='pg29-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 8'\r\n                    data-index='8'\r\n                    data-title='8'\r\n                    href='/Maze/index/8'\r\n                    onclick = 'show('8.PNG')'\r\n                    coords='56,210,85,305'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 40'\r\n                    data-index='40'\r\n                    data-title='40'\r\n                    href='/Maze/index/40'\r\n                    onclick = 'show('40.PNG')'\r\n                    coords='164,178,202,171,204,253,164,263'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 35'\r\n                    data-index='35'\r\n                    data-title='35'\r\n                    href='/Maze/index/35'\r\n                    onclick = 'show('35.PNG')'\r\n                    coords='452,160,537,220'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 2'\r\n                    data-index='2'\r\n                    data-title='2'\r\n                    href='/Maze/index/2'\r\n                    onclick = 'show('2.PNG')'\r\n                    coords='608,159,643,164,643,242,605,228,607,194'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 17'\r\n                    data-index='17'\r\n                    data-title='17'\r\n                    href='/Maze/index/17'\r\n                    onclick = 'show('17.PNG')'\r\n                    coords='368,369,419,369,421,411,356,414,357,404,364,393,369,379'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/29.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 30,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/30.PNG' usemap='#pg30-image-map' />\r\n                <map name='pg30-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 42'\r\n                    data-index='42'\r\n                    data-title='42'\r\n                    href='/Maze/index/42'\r\n                    onclick = 'show('42.PNG')'\r\n                    coords='130,32,186,48,186,102,130,96'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 34'\r\n                    data-index='34'\r\n                    data-title='34'\r\n                    href='/Maze/index/34'\r\n                    onclick = 'show('34.PNG')'\r\n                    coords='331,87,334,73,343,58,354,47,370,36,388,31,403,29,419,32,434,37,449,46,464,62,473,78,475,86,410,87'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 5'\r\n                    data-index='5'\r\n                    data-title='5'\r\n                    href='/Maze/index/5'\r\n                    onclick = 'show('5.PNG')'\r\n                    coords='616,46,666,31,667,92,616,98,617,71'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 15'\r\n                    data-index='15'\r\n                    data-title='15'\r\n                    href='/Maze/index/15'\r\n                    onclick = 'show('15.PNG')'\r\n                    coords='700,22,754,5,776,6,777,79,701,88'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/30.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 31,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/31.PNG' usemap='#pg31-image-map' />\r\n                <map name='pg31-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 44'\r\n                    data-index='44'\r\n                    data-title='44'\r\n                    href='/Maze/index/44'\r\n                    onclick = 'show('44.PNG')'\r\n                    coords='57,164,66,160,71,145,75,150,82,150,83,144,98,144,111,148,122,150,134,157,136,166,147,168,149,180,157,188,162,197,138,195,138,190,101,183,92,184,51,177'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 19'\r\n                    data-index='19'\r\n                    data-title='19'\r\n                    href='/Maze/index/19'\r\n                    onclick = 'show('19.PNG')'\r\n                    coords='267,212,274,204,275,193,280,197,287,192,302,193,319,198,329,204,327,210,335,212,337,220,342,230,315,224,291,220,265,215'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 21'\r\n                    data-index='21'\r\n                    data-title='21'\r\n                    href='/Maze/index/21'\r\n                    onclick = 'show('21.PNG')'\r\n                    coords='620,198,626,187,632,180,633,164,639,169,645,167,647,158,667,148,690,145,703,145,707,152,714,155,716,145,722,162,732,167,737,178,695,186,690,183,645,191,645,195'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/31.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 32,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/32.PNG' usemap='#pg32-image-map' />\r\n                <map name='pg32-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 11'\r\n                    data-index='11'\r\n                    data-title='11'\r\n                    href='/Maze/index/11'\r\n                    onclick = 'show('11.PNG')'\r\n                    coords='57,146,134,155,126,221,46,216'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 6'\r\n                    data-index='6'\r\n                    data-title='6'\r\n                    href='/Maze/index/6'\r\n                    onclick = 'show('6.PNG')'\r\n                    coords='376,96,390,99,401,100,416,99,425,93,430,100,430,122,425,133,419,144,406,157,399,165,387,145,379,126'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 28'\r\n                    data-index='28'\r\n                    data-title='28'\r\n                    href='/Maze/index/28'\r\n                    onclick = 'show('28.PNG')'\r\n                    coords='769,300,770,308,770,370,717,345,717,283'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 16'\r\n                    data-index='16'\r\n                    data-title='16'\r\n                    href='/Maze/index/16'\r\n                    onclick = 'show('16.PNG')'\r\n                    coords='203,372,265,327,287,453,242,538,237,541'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/32.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 33,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/33.PNG' usemap='#pg33-image-map' />\r\n                <map name='pg33-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 3'\r\n                    data-index='3'\r\n                    data-title='3'\r\n                    href='/Maze/index/3'\r\n                    onclick = 'show('3.PNG')'\r\n                    coords='98,169,107,144,112,117,106,113,131,50,150,174,98,179,100,173'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 35'\r\n                    data-index='35'\r\n                    data-title='35'\r\n                    href='/Maze/index/35'\r\n                    onclick = 'show('35.PNG')'\r\n                    coords='458,166,515,63,571,166'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 7'\r\n                    data-index='7'\r\n                    data-title='7'\r\n                    href='/Maze/index/7'\r\n                    onclick = 'show('7.PNG')'\r\n                    coords='642,173,666,53,682,114,676,117,676,134,680,147,687,160,691,168,682,173,681,178'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/33.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 34,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/34.PNG' usemap='#pg34-image-map' />\r\n                <map name='pg34-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 10'\r\n                    data-index='10'\r\n                    data-title='10'\r\n                    href='/Maze/index/10'\r\n                    onclick = 'show('10.PNG')'\r\n                    coords='39,11,55,11,73,21,89,24,99,26,103,30,108,56,114,72,121,82,82,77,71,75,56,75,48,62,40,44'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 25'\r\n                    data-index='25'\r\n                    data-title='25'\r\n                    href='/Maze/index/25'\r\n                    onclick = 'show('25.PNG')'\r\n                    coords='225,77,228,71,231,67,229,59,269,47,296,36,305,57,309,77,309,88,234,109'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/34.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 35,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/35.PNG' usemap='#pg35-image-map' />\r\n                <map name='pg35-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 33'\r\n                    data-index='33'\r\n                    data-title='33'\r\n                    href='/Maze/index/33'\r\n                    onclick = 'show('33.PNG')'\r\n                    coords='38,101,186,140'\r\n                    shape='rect' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/35.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 36,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/36.PNG' usemap='#pg36-image-map' />\r\n                <map name='pg36-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 7'\r\n                    data-index='7'\r\n                    data-title='7'\r\n                    href='/Maze/index/7'\r\n                    onclick = 'show('7.PNG')'\r\n                    coords='52,26,107,40,108,88,50,83'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 16'\r\n                    data-index='16'\r\n                    data-title='16'\r\n                    href='/Maze/index/16'\r\n                    onclick = 'show('16.PNG')'\r\n                    coords='222,60,309,60,310,99,226,100'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/36.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 37,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/37.PNG' usemap='#pg37-image-map' />\r\n                <map name='pg37-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 15'\r\n                    data-index='15'\r\n                    data-title='15'\r\n                    href='/Maze/index/15'\r\n                    onclick = 'show('15.PNG')'\r\n                    coords='40,120,50,106,63,93,84,85,112,83,134,86,149,95,164,112,168,129,170,142,33,142'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 10'\r\n                    data-index='10'\r\n                    data-title='10'\r\n                    href='/Maze/index/10'\r\n                    onclick = 'show('10.PNG')'\r\n                    coords='229,143,242,116,260,98,280,89,301,87,319,89,335,95,348,105,363,121,369,140,344,143'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 42'\r\n                    data-index='42'\r\n                    data-title='42'\r\n                    href='/Maze/index/42'\r\n                    onclick = 'show('42.PNG')'\r\n                    coords='419,143,421,127,429,113,438,101,450,89,464,82,478,78,501,76,518,80,535,89,550,100,558,112,567,129,568,144'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 20'\r\n                    data-index='20'\r\n                    data-title='20'\r\n                    href='/Maze/index/20'\r\n                    onclick = 'show('20.PNG')'\r\n                    coords='623,143,625,120,637,99,663,80,690,74,716,76,742,89,756,102,765,115,770,134,771,146'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/37.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 38,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/38.PNG' usemap='#pg38-image-map' />\r\n                <map name='pg38-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 40'\r\n                    data-index='40'\r\n                    data-title='40'\r\n                    href='/Maze/index/40'\r\n                    onclick = 'show('40.PNG')'\r\n                    coords='352,104,515,147'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 22'\r\n                    data-index='22'\r\n                    data-title='22'\r\n                    href='/Maze/index/22'\r\n                    onclick = 'show('22.PNG')'\r\n                    coords='584,118,645,101,645,159,584,169'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 43'\r\n                    data-index='43'\r\n                    data-title='43'\r\n                    href='/Maze/index/43'\r\n                    onclick = 'show('43.PNG')'\r\n                    coords='686,89,783,59,785,144,686,153'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/38.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 39,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/39.PNG' usemap='#pg39-image-map' />\r\n                <map name='pg39-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 11'\r\n                    data-index='11'\r\n                    data-title='11'\r\n                    href='/Maze/index/11'\r\n                    onclick = 'show('11.PNG')'\r\n                    coords='43,59,122,65,122,148,44,164'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 4'\r\n                    data-index='4'\r\n                    data-title='4'\r\n                    href='/Maze/index/4.PNG'\r\n                    onclick = 'show('4.PNG')'\r\n                    coords='192,71,246,76,244,128,193,136'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 12'\r\n                    data-index='12'\r\n                    data-title='12'\r\n                    href='/Maze/index/12'\r\n                    onclick = 'show('12.PNG')'\r\n                    coords='553,69,609,61,609,136,553,130'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/39.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 40,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/40.PNG' usemap='#pg40-image-map' />\r\n                <map name='pg40-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 11'\r\n                    data-index='11'\r\n                    data-title='11'\r\n                    href='/Maze/index/11'\r\n                    onclick = 'show('11.PNG')'\r\n                    coords='27,50,90,70,124,84,139,93,105,183,15,153,15,108'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 66'\r\n                    data-index='6'\r\n                    data-title='6'\r\n                    href='/Maze/index/6'\r\n                    onclick = 'show('6.PNG')'\r\n                    coords='228,151,318,135,324,151,324,202,235,218'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 38'\r\n                    data-index='38'\r\n                    data-title='38'\r\n                    href='/Maze/index/38'\r\n                    onclick = 'show('38.PNG')'\r\n                    coords='431,158,445,158,472,167,477,172,488,176,487,229,428,215'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/40.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 41,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/41.PNG' usemap='#pg41-image-map' />\r\n                <map name='pg41-image-map'>\r\n                <area\r\n                  target=''\r\n                  alt='door 1'\r\n                  data-index='1'\r\n                  data-title='1'\r\n                  href='/Maze/index/1'\r\n                  onclick = 'show('1.PNG')'\r\n                  coords='85,11,122,12,144,22,140,33,142,49,140,64,133,77,113,94,100,78,92,65,84,51,82,35,86,18'\r\n                  shape='poly' />\r\n\r\n                <area\r\n                  target=''\r\n                  alt='door 10'\r\n                  data-index='10'\r\n                  data-title='10'\r\n                  href='/Maze/index/10'\r\n                  onclick = 'show('10.PNG')'\r\n                  coords='353,51,446,51,444,58,444,78,442,92,437,103,425,112,409,122,401,128,388,117,374,111,361,105,357,89,357,60'\r\n                  shape='poly' />\r\n\r\n                <area\r\n                  target=''\r\n                  alt='door 38'\r\n                  data-index='38'\r\n                  data-title='38'\r\n                  href='/Maze/index/38'\r\n                  onclick = 'show('38.PNG')'\r\n                  coords='651,25,678,12,720,13,724,34,724,56,718,68,707,79,697,87,687,104,677,94,665,89,657,79,652,67,651,50,652,36'\r\n                  shape='poly' />\r\n              </map>\r\n            </img>\r\n            ", "../wwwroot/images/41.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 42,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/42.PNG' usemap='#pg42-image-map' />\r\n                <map name='pg42-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 22'\r\n                    data-index='22'\r\n                    data-title='22'\r\n                    href='/Maze/index/22'\r\n                    onclick = 'show('22.PNG')'\r\n                    coords='43,13,117,34,117,119,43,110'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 30'\r\n                    data-index='30'\r\n                    data-title='30'\r\n                    href='/Maze/index/30'\r\n                    onclick = 'show('30.PNG')'\r\n                    coords='153,48,205,66,208,129,156,122'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 4'\r\n                    data-index='4'\r\n                    data-title='4'\r\n                    href='/Maze/index/4.PNG'\r\n                    onclick = 'show('4.PNG')'\r\n                    coords='289,79,390,136'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 25'\r\n                    data-index='25'\r\n                    data-title='25'\r\n                    href='/Maze/index/25'\r\n                    onclick = 'show('25.PNG')'\r\n                    coords='467,79,574,136'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 37'\r\n                    data-index='37'\r\n                    data-title='37'\r\n                    href='/Maze/index/37'\r\n                    onclick = 'show('37.PNG')'\r\n                    coords='650,76,754,134'\r\n                    shape='rect' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/42.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 43,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/43.PNG' usemap='#pg43-image-map' />\r\n                <map name='pg43-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 22'\r\n                    data-index='22'\r\n                    data-title='22'\r\n                    href='/Maze/index/22'\r\n                    onclick = 'show('22.PNG')'\r\n                    coords='367,19,378,14,390,11,412,12,419,19,425,13,431,19,432,28,427,37,423,45,417,54,421,61,412,67,403,58,394,61,382,69,373,62,379,54,372,38'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 38'\r\n                    data-index='38'\r\n                    data-title='38'\r\n                    href='/Maze/index/38'\r\n                    onclick = 'show('38.PNG')'\r\n                    coords='359,447,422,520'\r\n                    shape='rect' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/43.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 44,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n            <img src='../wwwroot/images/44.PNG' usemap='#pg44-image-map' />\r\n              <map name='pg44-image-map'>\r\n                <area\r\n                  target=''\r\n                  alt='door 21'\r\n                  data-index='21'\r\n                  data-title='21'\r\n                  href='/Maze/index/21'\r\n                  onclick = 'show('21.PNG')'\r\n                  coords='259,204,263,191,275,179,285,173,299,168,309,168,320,172,330,177,336,183,341,192,348,201,351,215,345,218,256,219'\r\n                  shape='poly' />\r\n\r\n                <area\r\n                  target=''\r\n                  alt='door 18'\r\n                  data-index='18'\r\n                  data-title='18'\r\n                  href='/Maze/index/18'\r\n                  onclick = 'show('18.PNG')'\r\n                  coords='632,190,647,175,666,167,679,167,695,172,704,183,711,196,716,219,633,219'\r\n                  shape='poly' />\r\n              </map>\r\n            </img>\r\n          ", "../wwwroot/images/44.PNG" });

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 45,
                columns: new[] { "Doors", "Img" },
                values: new object[] { "\r\n              <img src='../wwwroot/images/45.PNG' usemap='#pg45-image-map' />\r\n                <map name='pg45-image-map'>\r\n                  <area\r\n                    target=''\r\n                    alt='door 28'\r\n                    data-index='28'\r\n                    data-title='28'\r\n                    href='/Maze/index/28'\r\n                    onclick = 'show('28.PNG')'\r\n                    coords='46,67,112,62,114,119,48,133'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 17'\r\n                    data-index='17'\r\n                    data-title='17'\r\n                    href='/Maze/index/17'\r\n                    onclick = 'show('17.PNG')'\r\n                    coords='166,57,210,53,211,102,169,112'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 36'\r\n                    data-index='36'\r\n                    data-title='36'\r\n                    href='/Maze/index/36'\r\n                    onclick = 'show('36.PNG')'\r\n                    coords='349,52,464,97'\r\n                    shape='rect' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 19'\r\n                    data-index='19'\r\n                    data-title='19'\r\n                    href='/Maze/index/19'\r\n                    onclick = 'show('19.PNG')'\r\n                    coords='601,97,601,50,647,54,647,107'\r\n                    shape='poly' />\r\n\r\n                  <area\r\n                    target=''\r\n                    alt='door 23'\r\n                    data-index='23'\r\n                    data-title='23'\r\n                    href='/Maze/index/23'\r\n                    onclick = 'show('23.PNG')'\r\n                    coords='699,58,762,63,761,127,699,116'\r\n                    shape='poly' />\r\n                </map>\r\n              </img>\r\n            ", "../wwwroot/images/45.PNG" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Doors",
                table: "Pages");

            migrationBuilder.DropColumn(
                name: "Img",
                table: "Pages");

            migrationBuilder.UpdateData(
                table: "Pages",
                keyColumn: "PageId",
                keyValue: 7,
                column: "Text",
                value: ". . . a pleasant room with three doors and a lamp. Looking at the picture on the wall they decided it wasn't a very good likeness. One of them almost fell over something on the floor. 'Why don’t they pick up after themselves?' he said, sounding like an old man. 'Weren’t you ever irresponsible?' I asked, thinking of my childhood and how wild I had been.Music was being played somewhere nearby. We stopped to listen for a moment. Leaving the picture looking out at an empty room we went on to . . .");
        }
    }
}
